/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AboutPage: typeof import('./pages/AboutPage.vue')['default']
        App: typeof import('./App.vue')['default']
        ContentIndex: typeof import('./Layout/Content/ContentIndex.vue')['default']
        Dropdown: typeof import('flowbite-vue')['Dropdown']
        EventCounter: typeof import('./components/EventCounter.vue')['default']
        FlowbiteThemable: typeof import('flowbite-vue')['FlowbiteThemable']
        HeaderIndex: typeof import('./Layout/Header/HeaderIndex.vue')['default']
        HelloWorld: typeof import('./components/HelloWorld.vue')['default']
        HomePage: typeof import('./pages/HomePage.vue')['default']
        ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
        LayoutIndex: typeof import('./Layout/LayoutIndex.vue')['default']
        ListGroup: typeof import('flowbite-vue')['ListGroup']
        ListGroupItem: typeof import('flowbite-vue')['ListGroupItem']
        MenuIndex: typeof import('./Layout/Menu/MenuIndex.vue')['default']
        Pages: typeof import('./pages/index.md')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }
}
