/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./pages/AboutPage.vue')['default']
    App: typeof import('./App.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Components: typeof import('./components/index.md')['default']
    ContentIndex: typeof import('./Layout/Content/ContentIndex.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EventCounter: typeof import('./components/EventCounter.vue')['default']
    HeaderIndex: typeof import('./Layout/Header/HeaderIndex.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomePage: typeof import('./pages/HomePage.vue')['default']
    ICarbonTerminal: typeof import('~icons/carbon/terminal')['default']
    LayoutIndex: typeof import('./Layout/LayoutIndex.vue')['default']
    MenuIndex: typeof import('./Layout/Menu/MenuIndex.vue')['default']
    Pages: typeof import('./pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
  }
}
