/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/vite-app-demo/': RouteRecordInfo<'/vite-app-demo/', '/vite-app-demo', Record<never, never>, Record<never, never>>,
    '/vite-app-demo/AboutPage': RouteRecordInfo<'/vite-app-demo/AboutPage', '/vite-app-demo/AboutPage', Record<never, never>, Record<never, never>>,
    '/vite-app-demo/HomePage': RouteRecordInfo<'/vite-app-demo/HomePage', '/vite-app-demo/HomePage', Record<never, never>, Record<never, never>>,
  }
}
